---
title: "graph"
author: "Yin-Ting Chou"
date: "5/14/2017"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE, results= "asis", fig.width = 10, fig.height= 6}
library(ggplot2)
datt=read.csv("/Users/chou/Google Drive/UMN2014-2016/Spring2016/Plan B/final/clean_dat.csv",header=TRUE)

area_hist=ggplot(datt, aes(x=Area))+ 
  geom_histogram(aes(x=Area,y=..density..),color="black",fill="darkgrey")+
  stat_density(position="identity",geom="line",size=1)+
  stat_function(fun=dgamma, colour="red",args =list(shape=2,scale=1183),size=1,
                linetype = "dashed")
ggsave(filename="area_hist.png", plot=area_hist)
```

```{r fig.width = 10, fig.height= 5}
p2=ggplot(datt, aes(x=Circularity))+ 
  geom_histogram(aes(x=Circularity,y=..density..),color="black",
                 fill="darkgrey")+
  stat_density(position="identity",geom="line",size=1)+
  stat_function(fun=dbeta, colour="red",args =list(shape1=15,shape2=5),size=1,
                linetype = "dashed")

pp= ggplot(datt, aes(x = Area, y = Circularity))+
  geom_point()

library(grid)
library(gridExtra)
a = grid.arrange(pp, p2, ncol = 2)
ggsave(filename="s_cir.png", plot=a)
```

